
server:
  tomcat:
#    port-header: X-Forwarded-Port
#    protocol_header: x-forwarded-proto
#    remote_ip_header: x-forwarded-for
    # 该线程池可以容纳的最大线程数。默认值：200；
    maxThreads: 300
    # 最大连接线程数，即：并发处理的最大请求数，默认值为 75
    maxConnections: 3000
    # 允许的最大连接数，应大于等于 maxProcessors ，默认值为 100
    acceptCount: 1000
    # 编码方式
    uri-encoding: UTF-8


spring:
  cloud:
    consul:
#      host: 192.168.1.102
#      port: 8500
      discovery:
        service-name: oa-operation-service
        prefer-ip-address: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://60.205.230.70:3306/hd_oa?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    password: root
    username: root
  #    这里采用的QQ邮箱测试
  mail:
    host: smtp.qq.com
    username: 2545251075@qq.com
    password: grqpjixakusedicc
    default-encoding: utf-8

application:
  base-package: com.js

mybatis:
  typeAliasesPackage: ${application.base-package}.pojo, ${application.base-package}.vo, ${application.base-package}.dto
  mapper-locations: classpath:mapper/*/*.xml,classpath:mapper/*.xml
  configuration:
    # 一定要设置，避免个别SQL执行时间过长，把系统搞跨
    default-statement-timeout: 5
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSq

logging:
  config: classpath:logback-spring.xml

#基本信息
info:
  description: 黑大OA签到平台
  version: v1.0
  author: 技术部
eureka:
  instance:
    # 使用 ip 代替实例名
#    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    #    encoder-name:
    #    register-with-eureka: false
    fetch-registry: false
  application:
    name: oa-operation-service